export const ModalItems = [
  {
    path: '/thumbs/Modal1.png',
    data: {
      id: 1,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Security Code',
      Content2: 'This code expires in 24 hours',
      Content3: 'Code',
      Content4: 'Continue',
      Content5: 'Cancel',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal2.png',
    data: {
      id: 2,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal2/img.svg',
      Content1: 'Install local now',
      Content2: 'We’ve gone native, try it!',
      Content3: 'Continue',
      Content4: 'Not now',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal3.png',
    data: {
      id: 3,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Delete your profile',
      Content2: 'Your profile will be automatically deleted after 1 month.',
      Content3: 'You won’t be able to access to your profile after 30.08.2021.',
      Content4: 'Delete my profile',
      Content5: 'Cancel',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      Color5: '#777777',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal4.png',
    data: {
      id: 4,
      Size: 'Medium',
      Position: 'Center',
      Content1: `The file is on it's way`,
      Content2: `You’ll get an notified when the receiver has opened the email.`,
      Content3: 'Go to dashboard',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal5.png',
    data: {
      id: 5,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'PLANS',
      Content2: `Choose best for you`,
      Content3: `Only pay for the capacity that you use.`,
      Content4: 'Continue',
      Content5: 'Cancel',
      Content6: 'Starter',
      Content7: '1 free (then $15 per meember / month)',
      Content8: 'Pro',
      Content9: '$19 per member/month',
      Content10: 'Business',
      Content11: '$29 per member/month',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      Color5: '#717791',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal6.png',
    data: {
      id: 6,
      Size: 'Medium',
      Position: 'Center',
      Content1: `Join our mail list`,
      Content2: `Save up to 30% of your next order`,
      Content3: 'Join now',
      Content4: 'Later',
      Content5: 'Enter your email',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal7.png',
    data: {
      id: 7,
      Size: 'Medium',
      Position: 'Center',
      Content1: `Hi, stranger`,
      Content2: `Sign up now, and get a 30% discount`,
      Content3: 'Log In',
      Content4: 'Sign up now',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal8.png',
    data: {
      id: 8,
      Size: 'Medium',
      Position: 'Center',
      Content1: `Subscribe to our newsletter`,
      Content2: `Receive the flash news in your inbox.`,
      Content3: 'Sign up now',
      Content4: 'Enter your email',
      Content5: 'By subscribe this form I agree to Privacy Policy.',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal9.png',
    data: {
      id: 9,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal9/img.svg',
      Content1: 'Hello stranger',
      Content2: `Sign up now and get 30% discount`,
      Content3: 'Sign up',
      Content4: 'Enter Full name',
      Content5: 'Enter your email',
      Content6: `Already have an account?`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal10.png',
    data: {
      id: 10,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Check your email',
      Content2: `Once you deletet your account, you’ll lose all data associatted with it.`,
      Content3: 'Sign up',
      Content4: 'Enter email',
      Content5: `Already have an account?`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal11.png',
    data: {
      id: 11,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal11/img.svg',
      Content1: 'Sign up',
      Content2: `Join new adventure`,
      Content3: 'Sign up',
      Content4: 'Enter Full name',
      Content5: 'Enter your email',
      Content6: `Forgot password`,
      Content7: `Log In`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal12.png',
    data: {
      id: 12,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal12/img.svg',
      Content1: 'Sign up',
      Content2: `Join new adventure`,
      Content3: 'Sign up',
      Content4: 'Enter Full name',
      Content5: 'Enter your email',
      Content6: `Forgot password`,
      Content7: `Log In`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal13.png',
    data: {
      id: 13,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Welcome to talk',
      Content3: `Let's get started`,
      Color1: '#000000',
      Content2: `Send friends photos, videos, locations, songs, voice messages, and more.`,
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal14.png',
    data: {
      id: 14,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal14/img.png',
      Content1: 'Jenny Yelriver',
      Content2: `@jennyyelriver`,
      Content3:
        'Duis eget elit erat. Aliam euismod, mauris quis tristique feugiat, elit diam tincidunt erat, nec fringilla odio orci dapibu magna. Vestibulum ultrices sem nec ex efficitur aliquam.',
      Content4: '10 SEP 2021 - 16:33 PM',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#777777',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal15.png',
    data: {
      id: 15,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Let’s feedback',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#BBBBBB',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal16.png',
    data: {
      id: 16,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Reminders',
      Content2: `How often would you like to be reminded to write?`,
      Content3: 'Daily',
      Content4: 'Weekly',
      Content5: 'No Reminders',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal17.png',
    data: {
      id: 17,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Don’t miss out',
      Content2: `Allow notifications get free ebook.`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal18.png',
    data: {
      id: 18,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Dark mode',
      Content2: `Just letting you know that we have dark mode.`,
      Content3: 'Eye relief',
      Content4:
        'With dark mode you won’t be giving your eyes shock in the morning.',
      Content5: 'Environment',
      Content6: `Change the mode depending in which place you’re at the moment.`,
      Content7: `Turn on dark mode`,
      Content8: 'Keep using light mode',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal19.png',
    data: {
      id: 19,
      Size: 'Medium',
      Position: 'Center',
      Logo: '/images/Modal19/Logo.svg',
      Content1: 'Hey there🥳',
      Content2: `We’re launching our product and we would be happy to have you.`,
      Content3: 'Sign up now',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal20.png',
    data: {
      id: 20,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Good job, Jenny',
      Content2: `Your profile is created!`,
      Content3: 'Go to my profile',
      Content4: 'Go to Home',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal21.png',
    data: {
      id: 21,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal21/img.png',
      Content1: 'Opps',
      Content2: `Page not found`,
      Content3: 'Go to Home',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal22.png',
    data: {
      id: 22,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal22/img.png',
      Content1: 'World Animal Day',
      Content2: `Animal Day is an international day of action for animal rights and welfare celebrated annually on October 4.`,
      Content3: 'Learn more',
      Color1: '#000000',
      Color2: '#FFFFFF',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal23.png',
    data: {
      id: 23,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Share this page',
      Content2: `If you liked this page you can share it on your social media.`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#1977F2',
      Color4: '#1E9BF0',
      Color5: '#E60022',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal24.png',
    data: {
      id: 24,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal24/img.svg',
      Content1: 'BE THE FIRST TO KNOW',
      Content2: `Sign up for email list and get our newest collection.`,
      Content3: 'Enter your email address',
      Content4: 'Subscribe',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal25.png',
    data: {
      id: 25,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal25/img.svg',
      Content1: 'LOVE NATURE?',
      Content3: 'Enter your email address',
      Content4: 'Subscribe',
      Content2: `Mauris feugiat egestas at llus tur pis massa, gravidez rum sit ameta.`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal26.png',
    data: {
      id: 26,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal26/img.svg',
      Content1: 'Sign up for our newsletter',
      Content2: `If you’re looking for a new way to promote your business that won’t cost you money.`,
      Content3: 'Enter your email address',
      Content4: 'Subscribe',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      AfterXSeconds: 3,
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal27.png',
    data: {
      id: 27,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal27/img.svg',
      Content1: 'Sign up for our newsletter',
      Content2: `GET 30% OF DISCOUNT`,
      Content3: 'Be the first to learn about new trends and offers.',
      Content4: 'Enter your email address',
      Content5: 'Women',
      Content6: `Men`,
      Content7: `Subscribe`,
      Color1: '#000000',
      Color2: '#717791',
      Color3: '#7D4AEA',
      Color4: '#FFFFFF',
      Color5: '#06B5D2',
      Color6: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal28.png',
    data: {
      id: 28,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal28/img.svg',
      Content1: 'Jenny Yelriver',
      Content2: `Creative Director`,
      Content3: 'Start your 14-day free trial today and shine.',
      Content4:
        'If you’re looking for a new way to promote your business that won’t cost you money.',
      Content5: 'Enter your email address',
      Content6: `Subscribe`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal29.png',
    data: {
      id: 29,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Get straight to growing your business well',
      Content2: `There’s good news for parents who have child born.`,
      Content3: 'Enter your email address',
      Content4: 'Enter your phone',
      Content5: 'Sign up',
      Content6: `I have an account`,
      Content7: `Forgot Password`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal30.png',
    data: {
      id: 30,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal30/img.svg',
      Content1: 'Jenny Yelriver',
      Content2: `Creative Director`,
      Content3: '5 reasons to purchase desktop computers',
      Content4:
        'Our award winning templates are the most beautiful way to present your ideas online.',
      Content5: 'Maybe Later',
      Content6: `Read Article`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal31.png',
    data: {
      id: 31,
      Size: 'Medium',
      Position: 'Center',
      Image: '/images/Modal31/bg.png',
      Logo: '/images/logo.svg',
      Content1: 'OVERVIEW',
      Content2: `Welcome to onboarding`,
      Content3:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur fermentum blandit.',
      Content4:
        'Quisque ultricies volutpat libero, ac pellentesque odio. Integer sodales euismod posuere.',
      Content5:
        'Our award winning templates are the most beautiful way to present your ideas online.',
      Content6: `Ut tempor vitae tortor eget iaculis. Aliquam volutpat tristique turpis ut cursus.`,
      Content7: `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      Color5: '#DDDDDD',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal32.png',
    data: {
      id: 32,
      Size: 'Medium',
      Position: 'Center',
      Logo: '/images/logo.svg',
      Content1: 'Do you like our design?',
      Content2: `Help us to improve it.`,
      Content3: 'Cool',
      Content4: 'Not Bad',
      Content5: 'Average',
      Content6: `Good`,
      Content7: `Bad`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#777777',
      Color4: '#BBBBBB',
      Color5: '#7D4AEA',
      Color6: '#F6F1FF',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal33.png',
    data: {
      id: 33,
      Size: 'Medium',
      Position: 'Center',
      Logo: '/images/logo.svg',
      Content1: 'Reach and grow your audiennce',
      Content2: `Build a better popup today.`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#777777',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal34.png',
    data: {
      id: 34,
      Size: 'Medium',
      Position: 'Center',
      Logo: '/images/logo.svg',
      Content1: 'tailwind',
      Content2: `Learn, share and connect with our community.`,
      Content3:
        'Explore our amazing products curated by our team just for you.',
      Content4: 'Join the club',
      Content5: 'Maybe Later',
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal35.png',
    data: {
      id: 35,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Ready to export',
      Content2: `Take action now.`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
  {
    path: '/thumbs/Modal36.png',
    data: {
      id: 36,
      Size: 'Medium',
      Position: 'Center',
      Content1: 'Save now',
      Content2: `Choose where you want to export.`,
      Content3: 'App Cloud',
      Content4: 'My Device',
      Content5: 'Download',
      Content6: `No, thanks`,
      Color1: '#000000',
      Color2: '#FFFFFF',
      Color3: '#7D4AEA',
      Color4: '#D2DAE3',
      AfterXSeconds: 3,
      SetAfterXSeconds: true,
      SetDevice: true,
      DeviceType: 'Desktop',
      SetAfterScroll: false,
      AfterScroll: 20,
      SetTrafficSource: false,
      SetLanguages: false,
      ExitIntent: false,
      isFormSubmission: false,
      isClickData: false,
    },
  },
];
